- hosts: all
  become: yes
  vars:
    network_addr: 130.79.92.30/25
    network_gateway: 130.79.92.126
    network_iface: eth0
    nameservers: [130.79.200.200]
    wifi_net: 192.168.142.0/24
    wifi_net6: fd01::/64
    wifi_ssid: Bite
    wifi_iface: wlan0

  handlers:
  - name: reapply netplan
    command: netplan apply

  - name: restart dnsmasq
    systemd:
      name: dnsmasq
      state: restarted

  - name: restart hostapd
    systemd:
      name: hostapd
      state: restarted

  tasks:
  - name: install a few packages
    apt:
      pkg:
      - aptitude
      - dnsmasq
      - hostapd
      - iptables-persistent

  - name: allow forwarding
    sysctl:
      name: '{{ item }}'
      value: '1'
    with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

  - name: configure interfaces
    template:
      src: netplan.yaml.j2
      dest: /etc/netplan/51-custom.yaml
    notify: reapply netplan

  - name: configure dnsmasq
    template:
      src: dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
    notify: restart dnsmasq

  - name: configure hostapd
    template:
      src: hostapd.conf.j2
      dest: /etc/hostapd/hostapd.conf
    notify: restart hostapd
