- name: install a few packages
  apt:
    pkg:
    - hostapd
    - iptables-persistent
    - isc-dhcp-server
    - radvd
    - bind9
  tags:
  - bind

- name: allow forwarding
  sysctl:
    name: '{{ item }}'
    value: '1'
  with_items:
  - net.ipv4.ip_forward
  - net.ipv6.conf.all.forwarding

- name: configure interfaces
  template:
    src: netplan.yaml.j2
    dest: /etc/netplan/51-custom.yaml
  notify: reapply netplan

- name: configure isc-dhcpd-server
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server

- name: configure radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
  notify: restart radvd
  tags: mip6d

- name: configure mip6d
  template:
    src: mip6d.conf.j2
    dest: /usr/local/etc/mip6d.conf
  tags: mip6d

- name: configure dummy interface
  template:
    src: 'network/{{ item }}.j2'
    dest: /etc/systemd/network/{{ item }}
  with_items:
    - homenet.netdev
    - homenet.network
  notify: restart networkd
  tags: dummy

- name: configure bind9
  template:
    src: 'bind/{{ item }}.j2'
    dest: /etc/bind/{{ item }}
  with_items:
    - named.conf.options
    - named.conf.local
  notify: restart bind
  tags: bind

- name: add entries to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item | ipaddr('net') | ipaddr('1') }}	{{ inventory_hostname }}.{{ domain }}"
  with_items:
  - '{{ wifi_net }}'
  - '{{ wifi_net6 }}'

- name: configure hostapd
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
  notify: restart hostapd

- name: enable and start net services
  systemd:
    name: '{{ item }}'
    enabled: yes
    masked: no
    state: started
  with_items:
  - hostapd
  - radvd
  - isc-dhcp-server
  - bind9

- name: enable NAT for IPv4
  iptables:
    ip_version: ipv4
    table: nat
    chain: POSTROUTING
    source: '{{ wifi_net }}'
    out_interface: eth0
    jump: MASQUERADE
  notify:
    - save iptables
    - restart hostapd

- name: enable NAT for IPv6
  iptables:
    ip_version: ipv6
    table: nat
    chain: POSTROUTING
    source: '{{ wifi_net6 }}'
    out_interface: eth0
    jump: MASQUERADE
  notify:
    - save iptables
    - restart hostapd
