- name: reapply netplan
  command: netplan apply

- name: restart isc-dhcp-server
  systemd:
    name: isc-dhcp-server
    state: restarted

- name: restart radvd
  systemd:
    name: radvd
    state: restarted

- name: restart networkd
  systemd:
    name: systemd-networkd
    state: restarted

- name: restart bind
  systemd:
    name: bind9
    state: restarted

- name: restart hostapd
  systemd:
    name: hostapd
    state: restarted

- name: save iptables
  command: netfilter-persistent save
