ansible_python_interpreter: /usr/bin/python3
# network_addr: 130.79.92.30/25
# network_gateway: 130.79.92.126
network_iface: eth0
nameservers: [ 1.1.1.1, 1.0.0.1 ]
wifi_net: 192.168.142.0/24
wifi_net6: fd01::/64
wifi_ssid: Noisette
wifi_iface: wlan0
domain: corp
