- name: setup multiple authorized keys
  authorized_key:
    user: '{{ item.1 }}'
    state: present
    key: "{{ lookup('file', item.0) }}"
  with_nested:
    - [ ludovicm67.pub, sandhose.pub ]
    - [ root, '{{ ansible_user }}' ]

- name: install a few packages
  apt:
    pkg:
    - aptitude
    - linux-tools-common
    - libdw1
    - libunwind8

- name: setup hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: setup timezone
  timezone:
    name: Europe/Paris
